repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
    - id: golangci-lint
      entry: golangci-lint run --new-from-rev HEAD --whole-files
      types: [go]
      language: golang
      require_serial: true
      pass_filenames: false
