# Build the manager binary
FROM --platform=$TARGETPLATFORM golang:alpine3.19 as builder
ARG TARGETOS
ARG TARGETARCH

RUN apk add --no-cache git bash

# Install Delve for debugging
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# Copy the go source
COPY cmd/main.go cmd/main.go
COPY api/ api/
COPY internal/ internal/
COPY pkg/ pkg/
