apiVersion: v1
kind: Secret
metadata:
  name: cosign-public-keys
stringData:
  key1.pub: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKPuCo9AmJCpqGWhefjbhkFcr1GA3
    iNa765seE3jYC3MGUe5h52393Dhy7B5bXGsg6EfPpNYamlAEWjxCpHF3Lg==
    -----END PUBLIC KEY-----
