//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuth) DeepCopyInto(out *BasicAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuth.
func (in *BasicAuth) DeepCopy() *BasicAuth {
	if in == nil {
		return nil
	}
	out := new(BasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EcrAuth) DeepCopyInto(out *EcrAuth) {
	*out = *in
	out.EcrCredentials = in.EcrCredentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EcrAuth.
func (in *EcrAuth) DeepCopy() *EcrAuth {
	if in == nil {
		return nil
	}
	out := new(EcrAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EcrCredentials) DeepCopyInto(out *EcrCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EcrCredentials.
func (in *EcrCredentials) DeepCopy() *EcrCredentials {
	if in == nil {
		return nil
	}
	out := new(EcrCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EcrRegistryRule) DeepCopyInto(out *EcrRegistryRule) {
	*out = *in
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EcrRegistryRule.
func (in *EcrRegistryRule) DeepCopy() *EcrRegistryRule {
	if in == nil {
		return nil
	}
	out := new(EcrRegistryRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciRegistryRule) DeepCopyInto(out *OciRegistryRule) {
	*out = *in
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciRegistryRule.
func (in *OciRegistryRule) DeepCopy() *OciRegistryRule {
	if in == nil {
		return nil
	}
	out := new(OciRegistryRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciValidator) DeepCopyInto(out *OciValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciValidator.
func (in *OciValidator) DeepCopy() *OciValidator {
	if in == nil {
		return nil
	}
	out := new(OciValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciValidatorList) DeepCopyInto(out *OciValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciValidatorList.
func (in *OciValidatorList) DeepCopy() *OciValidatorList {
	if in == nil {
		return nil
	}
	out := new(OciValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciValidatorSpec) DeepCopyInto(out *OciValidatorSpec) {
	*out = *in
	if in.OciRegistryRules != nil {
		in, out := &in.OciRegistryRules, &out.OciRegistryRules
		*out = make([]OciRegistryRule, len(*in))
		copy(*out, *in)
	}
	if in.EcrRegistryRules != nil {
		in, out := &in.EcrRegistryRules, &out.EcrRegistryRules
		*out = make([]EcrRegistryRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciValidatorSpec.
func (in *OciValidatorSpec) DeepCopy() *OciValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(OciValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciValidatorStatus) DeepCopyInto(out *OciValidatorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciValidatorStatus.
func (in *OciValidatorStatus) DeepCopy() *OciValidatorStatus {
	if in == nil {
		return nil
	}
	out := new(OciValidatorStatus)
	in.DeepCopyInto(out)
	return out
}
