apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-metrics-reader
  labels:
    app.kubernetes.io/created-by: validator-plugin-oci
    app.kubernetes.io/part-of: validator-plugin-oci
  {{- include "chart.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
