name: Create Issue

on:
  issues:
    types: [opened]

jobs:
  create-issue:
    uses: validator-labs/workflows/.github/workflows/issue.yaml@533081ac49a832a478062407e23e559db6545f1d # main
    secrets: inherit
